/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.time.OffsetDateTime;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 
 */
@JsonAdapter(CustomersPresence.Adapter.class)
public enum CustomersPresence {
  
  NOT_PRESENT("NOT_PRESENT"),
  
  VIRTUAL_PRESENT("VIRTUAL_PRESENT"),
  
  PHYSICAL_PRESENT("PHYSICAL_PRESENT");

  private String value;

  CustomersPresence(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CustomersPresence fromValue(String text) {
    for (CustomersPresence b : CustomersPresence.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CustomersPresence> {
    @Override
    public void write(final JsonWriter jsonWriter, final CustomersPresence enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CustomersPresence read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CustomersPresence.fromValue(String.valueOf(value));
    }
  }
}

