/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.time.OffsetDateTime;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The primary risk taker will have the main loss when one party of the contract does not fulfill the contractual duties.
 */
@JsonAdapter(PaymentPrimaryRiskTaker.Adapter.class)
public enum PaymentPrimaryRiskTaker {
  
  CUSTOMER("CUSTOMER"),
  
  MERCHANT("MERCHANT"),
  
  THIRD_PARTY("THIRD_PARTY");

  private String value;

  PaymentPrimaryRiskTaker(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PaymentPrimaryRiskTaker fromValue(String text) {
    for (PaymentPrimaryRiskTaker b : PaymentPrimaryRiskTaker.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<PaymentPrimaryRiskTaker> {
    @Override
    public void write(final JsonWriter jsonWriter, final PaymentPrimaryRiskTaker enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PaymentPrimaryRiskTaker read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PaymentPrimaryRiskTaker.fromValue(String.valueOf(value));
    }
  }
}

