/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wallee.sdk.model.CreationEntityState;
import com.wallee.sdk.model.DatabaseTranslatedString;
import com.wallee.sdk.model.PaymentTerminalDeviceManufacturer;
import com.wallee.sdk.model.Scope;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.*;
import java.time.OffsetDateTime;

/**
 * 
 */
public class PaymentTerminalDeviceModel {
  
  @SerializedName("description")
  protected DatabaseTranslatedString description = null;

  
  @SerializedName("id")
  protected Long id = null;

  
  @SerializedName("image")
  protected List<byte[]> image = null;

  
  @SerializedName("imageType")
  protected String imageType = null;

  
  @SerializedName("manufacturer")
  protected PaymentTerminalDeviceManufacturer manufacturer = null;

  
  @SerializedName("modelId")
  protected String modelId = null;

  
  @SerializedName("name")
  protected String name = null;

  
  @SerializedName("plannedPurgeDate")
  protected OffsetDateTime plannedPurgeDate = null;

  
  @SerializedName("scope")
  protected Scope scope = null;

  
  @SerializedName("state")
  protected CreationEntityState state = null;

  
  @SerializedName("title")
  protected DatabaseTranslatedString title = null;

  
  @SerializedName("version")
  protected Integer version = null;

  
  
   /**
   * 
   * @return description
  **/
  @ApiModelProperty(value = "")
  public DatabaseTranslatedString getDescription() {
    return description;
  }

  
   /**
   * The ID is the primary key of the entity. The ID identifies the entity uniquely.
   * @return id
  **/
  @ApiModelProperty(value = "The ID is the primary key of the entity. The ID identifies the entity uniquely.")
  public Long getId() {
    return id;
  }

  
   /**
   * 
   * @return image
  **/
  @ApiModelProperty(value = "")
  public List<byte[]> getImage() {
    return image;
  }

  
   /**
   * 
   * @return imageType
  **/
  @ApiModelProperty(value = "")
  public String getImageType() {
    return imageType;
  }

  
   /**
   * 
   * @return manufacturer
  **/
  @ApiModelProperty(value = "")
  public PaymentTerminalDeviceManufacturer getManufacturer() {
    return manufacturer;
  }

  
   /**
   * The model identifier of the device. The model identifier can be a number (e.g. a part number) or a name of the device model.
   * @return modelId
  **/
  @ApiModelProperty(value = "The model identifier of the device. The model identifier can be a number (e.g. a part number) or a name of the device model.")
  public String getModelId() {
    return modelId;
  }

  
   /**
   * 
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  
   /**
   * The planned purge date indicates when the entity is permanently removed. When the date is null the entity is not planned to be removed.
   * @return plannedPurgeDate
  **/
  @ApiModelProperty(value = "The planned purge date indicates when the entity is permanently removed. When the date is null the entity is not planned to be removed.")
  public OffsetDateTime getPlannedPurgeDate() {
    return plannedPurgeDate;
  }

  
   /**
   * 
   * @return scope
  **/
  @ApiModelProperty(value = "")
  public Scope getScope() {
    return scope;
  }

  
   /**
   * 
   * @return state
  **/
  @ApiModelProperty(value = "")
  public CreationEntityState getState() {
    return state;
  }

  
   /**
   * 
   * @return title
  **/
  @ApiModelProperty(value = "")
  public DatabaseTranslatedString getTitle() {
    return title;
  }

  
   /**
   * The version number indicates the version of the entity. The version is incremented whenever the entity is changed.
   * @return version
  **/
  @ApiModelProperty(value = "The version number indicates the version of the entity. The version is incremented whenever the entity is changed.")
  public Integer getVersion() {
    return version;
  }

  

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentTerminalDeviceModel paymentTerminalDeviceModel = (PaymentTerminalDeviceModel) o;
    return Objects.equals(this.description, paymentTerminalDeviceModel.description) &&
        Objects.equals(this.id, paymentTerminalDeviceModel.id) &&
        Objects.equals(this.image, paymentTerminalDeviceModel.image) &&
        Objects.equals(this.imageType, paymentTerminalDeviceModel.imageType) &&
        Objects.equals(this.manufacturer, paymentTerminalDeviceModel.manufacturer) &&
        Objects.equals(this.modelId, paymentTerminalDeviceModel.modelId) &&
        Objects.equals(this.name, paymentTerminalDeviceModel.name) &&
        Objects.equals(this.plannedPurgeDate, paymentTerminalDeviceModel.plannedPurgeDate) &&
        Objects.equals(this.scope, paymentTerminalDeviceModel.scope) &&
        Objects.equals(this.state, paymentTerminalDeviceModel.state) &&
        Objects.equals(this.title, paymentTerminalDeviceModel.title) &&
        Objects.equals(this.version, paymentTerminalDeviceModel.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, id, image, imageType, manufacturer, modelId, name, plannedPurgeDate, scope, state, title, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentTerminalDeviceModel {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    imageType: ").append(toIndentedString(imageType)).append("\n");
    sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    plannedPurgeDate: ").append(toIndentedString(plannedPurgeDate)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

