/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.time.OffsetDateTime;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 
 */
@JsonAdapter(RefundType.Adapter.class)
public enum RefundType {
  
  CUSTOMER_INITIATED_AUTOMATIC("CUSTOMER_INITIATED_AUTOMATIC"),
  
  CUSTOMER_INITIATED_MANUAL("CUSTOMER_INITIATED_MANUAL"),
  
  MERCHANT_INITIATED_ONLINE("MERCHANT_INITIATED_ONLINE"),
  
  MERCHANT_INITIATED_OFFLINE("MERCHANT_INITIATED_OFFLINE");

  private String value;

  RefundType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RefundType fromValue(String text) {
    for (RefundType b : RefundType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<RefundType> {
    @Override
    public void write(final JsonWriter jsonWriter, final RefundType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RefundType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RefundType.fromValue(String.valueOf(value));
    }
  }
}

