/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.wallee.sdk.model.DatabaseTranslatedString;
import com.wallee.sdk.model.SubscriptionProductComponentGroup;
import com.wallee.sdk.model.SubscriptionProductComponentReference;
import com.wallee.sdk.model.TaxClass;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.*;
import java.time.OffsetDateTime;

/**
 * 
 */
public class SubscriptionProductComponent {
  
  @SerializedName("componentChangeWeight")
  protected Integer componentChangeWeight = null;

  
  @SerializedName("componentGroup")
  protected SubscriptionProductComponentGroup componentGroup = null;

  
  @SerializedName("defaultComponent")
  protected Boolean defaultComponent = null;

  
  @SerializedName("description")
  protected DatabaseTranslatedString description = null;

  
  @SerializedName("id")
  protected Long id = null;

  
  @SerializedName("linkedSpaceId")
  protected Long linkedSpaceId = null;

  
  @SerializedName("maximalQuantity")
  protected BigDecimal maximalQuantity = null;

  
  @SerializedName("minimalQuantity")
  protected BigDecimal minimalQuantity = null;

  
  @SerializedName("name")
  protected DatabaseTranslatedString name = null;

  
  @SerializedName("quantityStep")
  protected BigDecimal quantityStep = null;

  
  @SerializedName("reference")
  protected SubscriptionProductComponentReference reference = null;

  
  @SerializedName("sortOrder")
  protected Integer sortOrder = null;

  
  @SerializedName("taxClass")
  protected TaxClass taxClass = null;

  
  @SerializedName("version")
  protected Integer version = null;

  
  
   /**
   * The change weight determines whether if a component change is considered as upgrade or downgrade. If product component with a weight 10 is changed to a product component with a weight 20, the change is considered as upgrade. On the other hand a change from 20 to 10 is considered as a downgrade.
   * @return componentChangeWeight
  **/
  @ApiModelProperty(value = "The change weight determines whether if a component change is considered as upgrade or downgrade. If product component with a weight 10 is changed to a product component with a weight 20, the change is considered as upgrade. On the other hand a change from 20 to 10 is considered as a downgrade.")
  public Integer getComponentChangeWeight() {
    return componentChangeWeight;
  }

  
   /**
   * 
   * @return componentGroup
  **/
  @ApiModelProperty(value = "")
  public SubscriptionProductComponentGroup getComponentGroup() {
    return componentGroup;
  }

  
   /**
   * When a component is marked as a &#39;default&#39; component it is used when no other component is selected by the user.
   * @return defaultComponent
  **/
  @ApiModelProperty(value = "When a component is marked as a 'default' component it is used when no other component is selected by the user.")
  public Boolean isDefaultComponent() {
    return defaultComponent;
  }

  
   /**
   * The component description may contain a longer description which gives the subscriber a better understanding of what the component contains.
   * @return description
  **/
  @ApiModelProperty(value = "The component description may contain a longer description which gives the subscriber a better understanding of what the component contains.")
  public DatabaseTranslatedString getDescription() {
    return description;
  }

  
   /**
   * The ID is the primary key of the entity. The ID identifies the entity uniquely.
   * @return id
  **/
  @ApiModelProperty(value = "The ID is the primary key of the entity. The ID identifies the entity uniquely.")
  public Long getId() {
    return id;
  }

  
   /**
   * The linked space id holds the ID of the space to which the entity belongs to.
   * @return linkedSpaceId
  **/
  @ApiModelProperty(value = "The linked space id holds the ID of the space to which the entity belongs to.")
  public Long getLinkedSpaceId() {
    return linkedSpaceId;
  }

  
   /**
   * The maximum quantity defines the maximum value which must be entered for the quantity.
   * @return maximalQuantity
  **/
  @ApiModelProperty(value = "The maximum quantity defines the maximum value which must be entered for the quantity.")
  public BigDecimal getMaximalQuantity() {
    return maximalQuantity;
  }

  
   /**
   * The minimal quantity defines the minimum value which must be entered for the quantity.
   * @return minimalQuantity
  **/
  @ApiModelProperty(value = "The minimal quantity defines the minimum value which must be entered for the quantity.")
  public BigDecimal getMinimalQuantity() {
    return minimalQuantity;
  }

  
   /**
   * The component name is shown to the subscriber. It should describe in few words what the component does contain.
   * @return name
  **/
  @ApiModelProperty(value = "The component name is shown to the subscriber. It should describe in few words what the component does contain.")
  public DatabaseTranslatedString getName() {
    return name;
  }

  
   /**
   * The quantity step defines at which interval the quantity can be increased.
   * @return quantityStep
  **/
  @ApiModelProperty(value = "The quantity step defines at which interval the quantity can be increased.")
  public BigDecimal getQuantityStep() {
    return quantityStep;
  }

  
   /**
   * The component reference is used to identify the component by external systems and it marks components to represent the same component within different product versions.
   * @return reference
  **/
  @ApiModelProperty(value = "The component reference is used to identify the component by external systems and it marks components to represent the same component within different product versions.")
  public SubscriptionProductComponentReference getReference() {
    return reference;
  }

  
   /**
   * The sort order controls in which order the component is listed. The sort order is used to order the components in ascending order.
   * @return sortOrder
  **/
  @ApiModelProperty(value = "The sort order controls in which order the component is listed. The sort order is used to order the components in ascending order.")
  public Integer getSortOrder() {
    return sortOrder;
  }

  
   /**
   * The tax class of the component determines the taxes which are applicable on all fees linked with the component.
   * @return taxClass
  **/
  @ApiModelProperty(value = "The tax class of the component determines the taxes which are applicable on all fees linked with the component.")
  public TaxClass getTaxClass() {
    return taxClass;
  }

  
   /**
   * The version number indicates the version of the entity. The version is incremented whenever the entity is changed.
   * @return version
  **/
  @ApiModelProperty(value = "The version number indicates the version of the entity. The version is incremented whenever the entity is changed.")
  public Integer getVersion() {
    return version;
  }

  

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionProductComponent subscriptionProductComponent = (SubscriptionProductComponent) o;
    return Objects.equals(this.componentChangeWeight, subscriptionProductComponent.componentChangeWeight) &&
        Objects.equals(this.componentGroup, subscriptionProductComponent.componentGroup) &&
        Objects.equals(this.defaultComponent, subscriptionProductComponent.defaultComponent) &&
        Objects.equals(this.description, subscriptionProductComponent.description) &&
        Objects.equals(this.id, subscriptionProductComponent.id) &&
        Objects.equals(this.linkedSpaceId, subscriptionProductComponent.linkedSpaceId) &&
        Objects.equals(this.maximalQuantity, subscriptionProductComponent.maximalQuantity) &&
        Objects.equals(this.minimalQuantity, subscriptionProductComponent.minimalQuantity) &&
        Objects.equals(this.name, subscriptionProductComponent.name) &&
        Objects.equals(this.quantityStep, subscriptionProductComponent.quantityStep) &&
        Objects.equals(this.reference, subscriptionProductComponent.reference) &&
        Objects.equals(this.sortOrder, subscriptionProductComponent.sortOrder) &&
        Objects.equals(this.taxClass, subscriptionProductComponent.taxClass) &&
        Objects.equals(this.version, subscriptionProductComponent.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(componentChangeWeight, componentGroup, defaultComponent, description, id, linkedSpaceId, maximalQuantity, minimalQuantity, name, quantityStep, reference, sortOrder, taxClass, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionProductComponent {\n");
    
    sb.append("    componentChangeWeight: ").append(toIndentedString(componentChangeWeight)).append("\n");
    sb.append("    componentGroup: ").append(toIndentedString(componentGroup)).append("\n");
    sb.append("    defaultComponent: ").append(toIndentedString(defaultComponent)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    linkedSpaceId: ").append(toIndentedString(linkedSpaceId)).append("\n");
    sb.append("    maximalQuantity: ").append(toIndentedString(maximalQuantity)).append("\n");
    sb.append("    minimalQuantity: ").append(toIndentedString(minimalQuantity)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    quantityStep: ").append(toIndentedString(quantityStep)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

