/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.*;
import java.time.OffsetDateTime;

/**
 * The component reference configuration adjusts the product component for a particular subscription.
 */
public class SubscriptionComponentReferenceConfiguration {
  
  @SerializedName("productComponentReferenceId")
  protected Long productComponentReferenceId = null;

  
  @SerializedName("quantity")
  protected BigDecimal quantity = null;

  
  
  public SubscriptionComponentReferenceConfiguration productComponentReferenceId(Long productComponentReferenceId) {
    this.productComponentReferenceId = productComponentReferenceId;
    return this;
  }

   /**
   * 
   * @return productComponentReferenceId
  **/
  @ApiModelProperty(value = "")
  public Long getProductComponentReferenceId() {
    return productComponentReferenceId;
  }

  public void setProductComponentReferenceId(Long productComponentReferenceId) {
    this.productComponentReferenceId = productComponentReferenceId;
  }

  
  public SubscriptionComponentReferenceConfiguration quantity(BigDecimal quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * 
   * @return quantity
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getQuantity() {
    return quantity;
  }

  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionComponentReferenceConfiguration subscriptionComponentReferenceConfiguration = (SubscriptionComponentReferenceConfiguration) o;
    return Objects.equals(this.productComponentReferenceId, subscriptionComponentReferenceConfiguration.productComponentReferenceId) &&
        Objects.equals(this.quantity, subscriptionComponentReferenceConfiguration.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productComponentReferenceId, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionComponentReferenceConfiguration {\n");
    
    sb.append("    productComponentReferenceId: ").append(toIndentedString(productComponentReferenceId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

