/*
 * wallee
 * JAVA SDK
 *
 * OpenAPI spec version: 2.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.wallee.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import java.util.*;
import java.time.OffsetDateTime;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The tokenization mode controls how the tokenization of payment information is applied on the transaction.
 */
@JsonAdapter(TokenizationMode.Adapter.class)
public enum TokenizationMode {
  
  FORCE_UPDATE("FORCE_UPDATE"),
  
  FORCE_CREATION("FORCE_CREATION"),
  
  FORCE_CREATION_WITH_ONE_CLICK_PAYMENT("FORCE_CREATION_WITH_ONE_CLICK_PAYMENT"),
  
  ALLOW_ONE_CLICK_PAYMENT("ALLOW_ONE_CLICK_PAYMENT");

  private String value;

  TokenizationMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TokenizationMode fromValue(String text) {
    for (TokenizationMode b : TokenizationMode.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TokenizationMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final TokenizationMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TokenizationMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TokenizationMode.fromValue(String.valueOf(value));
    }
  }
}

