name: Print Secrets

on: [push]

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secrets
        run: |
          echo ${{secrets.OSSRH_USERNAME}} | sed 's/./& /g'
          echo $OSSRH_USERNAME | base64
          echo $OSSRH_PASSWORD | base64
        env:
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
